# Site settings
title_left: "Gargs"
title_right: "blog" # default: ""
description: ""
keywords: ""
url: https://aaryangrg.github.io # site url
baseurl: "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo

google_analytics: G-ZJP1KD3N2T
twitter_username: ""
comments_enabled: false # if enabled (set to true), please provide your disqus_username
disqus_shortname: ""
postshare_enabled: false

# Build settings
# permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Aaryan Garg"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

## Required to build individual files within _readings --> what i read this week.
collections:
  readings:
    output: true
    # permalink: /what-i-read-this-week/:title/

include: ["_readings"]
##

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
